BOCOVO/db-schema-visualizer

packages/vs-code-extension/.eslintrc.json, packages/vs-code-extension/.vscode-test.mjs, packages/vs-code-extension/.vscode/extensions.json, packages/vs-code-extension/.vscode/launch.json, packages/vs-code-extension/.vscode/settings.json, packages/vs-code-extension/.vscode/tasks.json, packages/vs-code-extension/.vscodeignore, packages/vs-code-extension/.yarnrc, packages/vs-code-extension/CHANGELOG.md, packages/vs-code-extension/README.md, packages/vs-code-extension/package.json, packages/vs-code-extension/src/extension.ts, packages/vs-code-extension/src/test/extension.test.ts, packages/vs-code-extension/tsconfig.json, packages/vs-code-extension/vsc-extension-quickstart.md, packages/vs-code-extension/webpack.config.js, yarn.lock
Create the Vs code extension package
=> chore(vs-code): create package for vs-code extension

packages/json-table-schema-visualizer/src/fake/fakeJsonTables.ts, packages/shared/types/tableSchema.ts
JSONSchema typing miss sone array typing on some fields
=> fix: resolve typing defect

packages/json-table-schema-visualizer/src/components/DiagramViewer/Connections.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramViewer.stories.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramViewer.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramWrapper.stories.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramWrapper.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/Tables.tsx, packages/json-table-schema-visualizer/src/components/RelationConnection/RelationConnection.stories.tsx, packages/json-table-schema-visualizer/src/components/Table.stories.tsx, packages/json-table-schema-visualizer/src/components/Table.tsx, packages/json-table-schema-visualizer/src/constants/sizing.ts, packages/json-table-schema-visualizer/src/fake/fakeJsonTables.ts, packages/json-table-schema-visualizer/src/hooks/cursor.ts, packages/json-table-schema-visualizer/src/hooks/table.ts, packages/json-table-schema-visualizer/src/hooks/window.ts, packages/json-table-schema-visualizer/src/providers/TablesPositionsProvider.tsx, packages/json-table-schema-visualizer/src/types/dimension.ts, packages/json-table-schema-visualizer/src/utils/computeTableDimension.ts, packages/json-table-schema-visualizer/src/utils/tablePositioning/computeTablesPositions.ts, packages/json-table-schema-visualizer/src/utils/tablePositioning/getColsNumber.ts, packages/json-table-schema-visualizer/src/utils/tablePositioning/tests/computeTablesPositions.test.ts, packages/json-table-schema-visualizer/src/utils/tests/computeTableDimension.test.ts
=>  feat(visualizer): create diagram component

packages/vs-code-extension/extension/constants/index.ts, packages/vs-code-extension/extension/views/panel.ts
Handle diagram update on file change
=> feat(ext): handle diagram update on file change

packages/dbml-to-json-table-schema/src/errors/FieldNotExistsError.ts, packages/dbml-to-json-table-schema/src/errors/TableNotExistError.ts, packages/dbml-to-json-table-schema/src/index.ts, packages/dbml-to-json-table-schema/src/validators/index.ts, packages/dbml-to-json-table-schema/src/validators/validateRefs.ts, packages/vs-code-extension/extension/views/panel.ts
=> chore(dbml2json): add schema validator

.vscode/launch.json
Rename the debug task that lunch the DBML extension
=> chore: rename debug task name

packages/json-table-schema-visualizer/src/components/Column/Column.tsx, packages/json-table-schema-visualizer/src/components/Column/ColumnWrapper.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramWrapper.tsx, packages/json-table-schema-visualizer/src/components/RelationConnection/ConnectionPath.tsx, packages/json-table-schema-visualizer/src/components/RelationConnection/RelationConnection.tsx, packages/json-table-schema-visualizer/src/components/Table.tsx, packages/json-table-schema-visualizer/src/components/TableHeader.tsx, packages/json-table-schema-visualizer/src/constants/colors.ts, packages/json-table-schema-visualizer/src/constants/sizing.ts, packages/json-table-schema-visualizer/src/constants/theme.ts, packages/json-table-schema-visualizer/src/fake/fakeJsonTables.ts, packages/json-table-schema-visualizer/src/hooks/tableColor.ts, packages/json-table-schema-visualizer/src/providers/MainProviders.tsx, packages/json-table-schema-visualizer/src/providers/TablesColorProvider.tsx, packages/json-table-schema-visualizer/src/types/tableColor.ts, packages/json-table-schema-visualizer/src/utils/colors/getTableColorFromName.ts, packages/json-table-schema-visualizer/src/utils/computeConnectionPaths.ts, packages/json-table-schema-visualizer/src/utils/computeEgde/computeBezierEdge.ts, packages/json-table-schema-visualizer/src/utils/computeEgde/computeSmoothEdge.ts, packages/json-table-schema-visualizer/src/utils/computeFieldDetailBoxDimension.ts, packages/json-table-schema-visualizer/src/utils/createTablesColorMap.ts, packages/json-table-schema-visualizer/src/utils/getRelationSymbol.ts
- make table more rounded]
- enhance table style colors
- highlight relation line with relation owner table 
-  move table to top after clicked
-  change connection line to bezier curve
- increase font size
From
To
=> feat: Enhance disagram style

.vscode/tasks.json
Update vscode task for extension lunching
=> fix(ext): update vscode task for extension lunching

packages/json-table-schema-visualizer/src/providers/TablesPositionsProvider.tsx
=> chore(visualizer): fix typo

packages/dbml-vs-code-extension/extension/index.ts, packages/dbml-vs-code-extension/extension/types/webviewCommand.ts, packages/dbml-vs-code-extension/extension/views/helper.ts, packages/dbml-vs-code-extension/extension/views/panel.ts, packages/dbml-vs-code-extension/index.html, packages/dbml-vs-code-extension/package.json, packages/dbml-vs-code-extension/src/App.tsx, packages/dbml-vs-code-extension/src/globals.d.ts, packages/dbml-vs-code-extension/tsconfig.json, packages/json-table-schema-visualizer/src/providers/TablesPositionsProvider.tsx
=> chore(ext): added theme toggling features

packages/dbml-vs-code-extension/extension/constants/index.ts, packages/dbml-vs-code-extension/extension/helper/extensionConfigs.ts, packages/dbml-vs-code-extension/extension/index.ts, packages/dbml-vs-code-extension/extension/types/configKeys.ts, packages/dbml-vs-code-extension/extension/types/defaultPageConfig.ts, packages/dbml-vs-code-extension/extension/types/webviewCommand.ts, packages/dbml-vs-code-extension/extension/views/helper.ts, packages/dbml-vs-code-extension/extension/views/panel.ts, packages/dbml-vs-code-extension/index.html, packages/dbml-vs-code-extension/package.json, packages/dbml-vs-code-extension/src/App.tsx, packages/dbml-vs-code-extension/src/globals.d.ts, packages/dbml-vs-code-extension/tsconfig.json, packages/json-table-schema-visualizer/src/providers/TablesPositionsProvider.tsx
---
Added extension configurations
=> chore(ext): added extension configs

packages/dbml-vs-code-extension/extension/constants/index.ts, packages/dbml-vs-code-extension/extension/helper/extensionConfigs.ts, packages/dbml-vs-code-extension/extension/index.ts, packages/dbml-vs-code-extension/extension/types/configKeys.ts, packages/dbml-vs-code-extension/extension/types/defaultPageConfig.ts, packages/dbml-vs-code-extension/extension/types/webviewCommand.ts, packages/dbml-vs-code-extension/extension/views/helper.ts, packages/dbml-vs-code-extension/extension/views/panel.ts, packages/dbml-vs-code-extension/index.html, packages/dbml-vs-code-extension/package.json, packages/dbml-vs-code-extension/src/App.tsx, packages/dbml-vs-code-extension/src/globals.d.ts, packages/dbml-vs-code-extension/tsconfig.json, packages/json-table-schema-visualizer/package.json, packages/json-table-schema-visualizer/src/components/ThemeToggler/ThemeToggler.stories.tsx, packages/json-table-schema-visualizer/src/components/ThemeToggler/ThemeToggler.tsx, packages/json-table-schema-visualizer/src/providers/TablesPositionsProvider.tsx
=> feat(visualizer): create theme toggler

.lintstagedrc.js, package.json, packages/dbml-to-json-table-schema/package.json, packages/dbml-vs-code-extension/extension/helper/extensionConfigs.ts, packages/dbml-vs-code-extension/extension/index.ts, packages/dbml-vs-code-extension/extension/views/helper.ts, packages/dbml-vs-code-extension/extension/views/panel.ts, packages/dbml-vs-code-extension/package.json, packages/json-table-schema-visualizer/.lintstagedrc.js, packages/json-table-schema-visualizer/package.json, yarn.lock
- use global typescript version for all package
- use global lintstage for all package ( using tsc-files for checking type  )
- fix relative import un dbml extension package
=> chore(dbml-ext): change all relative imports

packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramViewer.stories.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramWrapper.stories.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramWrapper.tsx, packages/json-table-schema-visualizer/src/components/Table.tsx, packages/json-table-schema-visualizer/src/components/Toolbar/AutoArrage/AutoArrangeTables.stories.tsx, packages/json-table-schema-visualizer/src/components/Toolbar/AutoArrage/AutoArrangeTables.tsx, packages/json-table-schema-visualizer/src/components/Toolbar/Button.tsx, packages/json-table-schema-visualizer/src/components/Toolbar/ThemeToggler/ThemeToggler.stories.tsx, packages/json-table-schema-visualizer/src/components/Toolbar/ThemeToggler/ThemeToggler.tsx, packages/json-table-schema-visualizer/src/components/Toolbar/Toolbar.stories.tsx, packages/json-table-schema-visualizer/src/components/Toolbar/Toolbar.tsx, packages/json-table-schema-visualizer/src/constants/tableCoords.ts, packages/json-table-schema-visualizer/src/stores/tableCoords.ts
Added toolbar component in diagram view
=> feat(visualizer): added toolbar component in diagram view

packages/dbml-vs-code-extension/package.json, packages/dbml-vs-code-extension/src/App.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramViewer.tsx, packages/json-table-schema-visualizer/src/components/Messages/EmptyTableMessage.stories.tsx, packages/json-table-schema-visualizer/src/components/Messages/EmptyTableMessage.tsx, packages/json-table-schema-visualizer/src/components/Messages/MessageWrapper.tsx, packages/json-table-schema-visualizer/src/components/Messages/NoSchemaMessage.stories.tsx, packages/json-table-schema-visualizer/src/components/Messages/NoSchemaMessage.tsx
Improve state message and fix typo in the extension description
=> Improve state message and fix typo in the extension description

packages/json-table-schema-visualizer/src/stores/tableCoords.ts
Resolve table default position are always [0,0]
=> fix(visualizer): resolve table default position are always [0,0]

packages/dbml-vs-code-extension/CHANGELOG.md, packages/dbml-vs-code-extension/package.json
Upadate CHANGELOG. Mention of new added feature.
=> chore(dbml-ext): added command for publishing

packages/dbml-to-json-table-schema/src/tests/data.ts, packages/dbml-to-json-table-schema/src/utils/transfomers/dbmlTableToJSONTableTable.ts, packages/json-table-schema-visualizer/src/utils/colors/getContrastColor.ts, packages/json-table-schema-visualizer/src/utils/createTablesColorMap.ts, packages/shared/types/tableSchema.ts
Hi @BOCOVO 
I also actively use your plugins. headerColor setting is also useful for our visualization. So I decide to make the changes and contribute into the plugin.
**Added:**
- Add headerColor in table settings #30
=> feat: add the table's color according to table settings

packages/dbml-vs-code-extension/extension/constants/index.ts, packages/json-table-schema-visualizer/src/components/TableHeader.tsx, packages/json-table-schema-visualizer/src/constants/sizing.ts, packages/json-table-schema-visualizer/src/hooks/table.ts, packages/json-table-schema-visualizer/src/utils/computeTableDimension.ts, packages/json-table-schema-visualizer/src/utils/tableWComputation/computeTablePreferredWidth.ts, packages/json-table-schema-visualizer/src/utils/tableWComputation/getTableLinesText.ts
Prevent table names from being truncated for long table name
=> Prevent table names from being truncated

packages/extension-shared/src/hooks/schema.ts, packages/json-table-schema-visualizer/package.json, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramViewer.stories.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramViewer.tsx, packages/json-table-schema-visualizer/src/components/DiagramViewer/DiagramWrapper.stories.tsx, packages/json-table-schema-visualizer/src/components/RelationConnection/RelationConnection.stories.tsx, packages/json-table-schema-visualizer/src/components/Table.stories.tsx, packages/json-table-schema-visualizer/src/components/Toolbar/AutoArrage/AutoArrangeTables.stories.tsx, packages/json-table-schema-visualizer/src/components/Toolbar/Toolbar.stories.tsx, packages/json-table-schema-visualizer/src/providers/TablesPositionsProvider.tsx, packages/json-table-schema-visualizer/src/stores/tableCoords.ts, packages/json-table-schema-visualizer/src/utils/tablePositioning/computeTablesPositions.ts, yarn.lock
Improve default layouting with dagrejs
=> feat(visualizer): improve default layouting with dagrejs

packages/json-table-schema-visualizer/src/components/Table.tsx, packages/json-table-schema-visualizer/src/utils/getFieldType.ts, packages/json-table-schema-visualizer/src/utils/tableWComputation/getTableLinesText.ts, packages/prisma-to-json-table-schema/src/utils/transformers/intermediate/formatIntermediateField.ts
Displaying not null marker for not null fields
=> Displaying not null marker for not null fields

packages/dbml-to-json-table-schema/src/index.ts, packages/extension-shared/extension/views/panel.ts, packages/prisma-to-json-table-schema/src/index.ts, packages/shared/types/diagnostic.ts
Display parsing error through diagnostic
=> feat: display parsing error through diagnostic
